repository:
  name: SparkEngineWeb
  description: SparkEngineWeb is a Typescript GameEngine that aims to run in the Browser and in Browser based solutions
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  has_releases: true
  has_packages: true
  has_deployments: true

branches:
  - name: "main"
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: false
        contexts:
          - "Build"
          - "Visual Tests / Visual Tests"
          - "Performance Tests"
          - "Unit Tests"

      enforce_admins: false
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: false
      lock_branch: false
      allow_fork_syncing: false
      bypass_pull_request_allowances:
        apps:
          - github-actions[bot]
        users: []
        teams: []

